const ROW_HEIGHT = 50;
const START_HEIGHT = 100;
const FINISH_HEIGHT = 100;
const BOARD_HEIGHT = 800;
const BOARD_WIDTH = 1000;

export { ROW_HEIGHT, START_HEIGHT, FINISH_HEIGHT, BOARD_HEIGHT, BOARD_WIDTH };
